version: '3.8'

services:
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
